### ISSUE TITLE
Option to remove the background color

### ISSUE THREAD

**Issue by ghost** [Username-08/lightnovel-cli#1]
My colorscheme looks really bad with that background. It would be really cool if there was a way to disable the background. I'm talking about this:

![image](https://user-images.githubusercontent.com/90166733/159161687-7e2e6ce5-5a7b-4c0a-921e-5cf8873d11d7.png)

Awesome CLI btw!

**Comment by Username-08** [comment]
Hi, Sorry for the late response, 
I've changed it to use the default terminal background now

**Comment by ghost** [comment]
Thanks!
